---
title: "CV"
---

<br/>

##  Lorenzo Braschi 
__Warsaw, Poland__  
__Personal Email__: lbraschi (at) gmail (dot) com

<br/>

## Summary

<br/>

I have ten years of analytical experience in making data understandable to the non-expert. My main areas of expertise lie in the application of advanced analytical techniques to extract information, and in the deployment of the visualization tools necessary for understanding the data.   
I am proficient in a wide variety of areas, from statistical modelling to data visualization, web mining, database querying, and others.    
I am an advanced R programmer and an evangelist of reproducible research methodologies.    

---------

<br/>

## Experience

<br/>

##### **IT Expert (Data Science) at Roche**  
_2017 - Current_ 

##### **Statistical Consultant at Accenture**
_2015 - 2017_

Design and implementation of data products that enhanced business strategic vision of technology and retail customers in a B2B.   
Drove adoption of reproducible research technologies using R and automated reporting for both the company and the customers.   
Building R Shiny dasboards for the visualization of financial data. 

###### **Large international supermarket chain (as a consultant from Accenture Analytics)**
_2017_
Customer segmentation using principal components and random forests. 

###### **Large jewelry retailer  (as a consultant from Accenture Analytics)**
_2016 - 2017_
Collaborated in the upgrade of the customers and stores database. 

###### **Large technology retailer (as a consultant from Accenture Analytics**
_2015 - 2016_
Helped identify major bottlenecks in the delivery process from production to physical stores using sales data from all EMEIA countries. 

##### **Clinical Trials Analyst, Sermes CRO **
_2014 - 2015_

Design, analysis and reporting of clinical drug trials. 

##### **Assistant Professor of Statistics, Universidad Alfonso X el Sabio** 
_2011 - 2015_

Lecturer of Statistics and Methodology for the Health Sciences.

##### **Lab Technician, Faculty of Psychology, Universidad Autónoma de Madrid **
_2009 - 2010_

Design of experiments and data analysis for the Language Learning Babylab. 



